name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # Install OpenCL
    - name: Install OpenCL
      run: |
        sudo apt-get update
        sudo apt-get install -y opencl-headers ocl-icd-opencl-dev pocl-opencl-icd

    - name: Cache Boost
      id: cache-boost
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/boost_install
        key: ubuntu-boost-1.83.0-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: ubuntu-boost-1.83.0-

    - name: Install Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        echo "使用 apt 安装 Boost"
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev

        # 验证安装
        dpkg -l | grep libboost

        # 设置环境变量
        echo "BOOST_ROOT=/usr" >> $GITHUB_ENV
        echo "BOOST_LIBRARYDIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV

    - name: Set Boost environment variables
      run: |
        echo "BOOST_ROOT=${{ github.workspace }}/boost_install" >> $GITHUB_ENV
        echo "BOOST_LIBRARYDIR=${{ github.workspace }}/boost_install/lib" >> $GITHUB_ENV
        echo "Setting Boost variables:"
        echo "BOOST_ROOT=$BOOST_ROOT"
        echo "BOOST_LIBRARYDIR=$BOOST_LIBRARYDIR"

    - name: Debug Environment
      run: |
        echo "Current directory: ${{ github.workspace }}"
        echo "CMake version:"
        cmake --version
        echo "BOOST_ROOT: ${{ env.BOOST_ROOT }}"
        echo "BOOST_LIBRARYDIR: ${{ env.BOOST_LIBRARYDIR }}"
        echo "Contents of BOOST_ROOT:"
        if [ -d "$BOOST_ROOT" ]; then
          ls -la "$BOOST_ROOT"
        else
          echo "BOOST_ROOT directory does not exist"
        fi
        echo "Contents of BOOST_LIBRARYDIR:"
        if [ -d "$BOOST_LIBRARYDIR" ]; then
          ls -la "$BOOST_LIBRARYDIR"
        else
          echo "BOOST_LIBRARYDIR directory does not exist"
        fi
        echo "OpenCL Status:"
        dpkg -l | grep -i opencl

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT="${{ env.BOOST_ROOT }}" -DBOOST_LIBRARYDIR="${{ env.BOOST_LIBRARYDIR }}" -DBoost_DEBUG=ON -DBoost_DETAILED_FAILURE_MSG=ON -DUSE_OPENCL=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Run Google Tests
      run: ./build/gtest_unitTest

    - name: Upload CMake logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cmake-logs-ubuntu
        path: |
          ${{github.workspace}}/build/CMakeFiles/CMakeOutput.log
          ${{github.workspace}}/build/CMakeFiles/CMakeError.log

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-ubuntu
        path: ${{github.workspace}}/build
